version: '3.8'
services:
  postgres:
    image: postgres:15  # Cambiar a la versión 15
    restart: always
    environment:
      POSTGRES_DB: managerDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  backend-service:
    build:
      context: ./apps/api-demo
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:password123@postgres:5432/managerDB
    ports:
      - "3001:3001"

  frontend-service:
    build:
      context: ./apps/client-demo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
